FROM loongcr.lcpu.dev/lcpu/archlinux:base
RUN pacman -Syyu --noconfirm && pacman -S --noconfirm --needed git git-lfs openssh curl perl && pacman -Scc --noconfirm

ADD posix/* /usr/local/bin/

# RUN adduser -g Drone -s /bin/sh -D -u 1000 drone
# RUN echo 'drone ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/drone
# USER drone:drone
# RUN chmod -R 777 /home/drone

ENTRYPOINT ["/usr/local/bin/clone"]
